name: Benchmark
on:
  push: {}
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  detect-commit:
    runs-on: ubuntu-24.04
    outputs:
      commit: ${{ steps.detect-commit.outputs.COMMIT }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Detect submodule commit
        run: echo "COMMIT=$(git log -1 --format='%H')" >> $GITHUB_OUTPUT
        id: detect-commit
        working-directory: ./upstream

  publish-docker-images-with-docker:
    name: Build with Docker
    runs-on: ubuntu-latest
    needs: [detect-commit]
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - ""
          - "-conda"
          - "-kubernetes"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: PrefectHQ/prefect
          ref: ${{ needs.detect-commit.outputs.commit }}
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            NODE_VERSION=18.18.0
            ${{ ( endsWith(matrix.flavor, 'conda') && 'BASE_IMAGE=prefect-conda' ) || '' }}
            ${{ ( endsWith(matrix.flavor, 'kubernetes') && 'PREFECT_EXTRAS=[redis,kubernetes]' ) || '' }}
          pull: true
          provenance: false

  publish-docker-images-with-depot:
    name: Build with Depot
    runs-on: depot-ubuntu-latest
    needs: [detect-commit]
    strategy:
      fail-fast: false
      matrix:
        flavor:
          - ""
          - "-conda"
          - "-kubernetes"
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v4
        with:
          repository: PrefectHQ/prefect
          ref: ${{ needs.detect-commit.outputs.commit }}
          fetch-depth: 0
      - uses: depot/setup-action@v1

      - uses: depot/build-push-action@v1
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
            NODE_VERSION=18.18.0
            ${{ ( endsWith(matrix.flavor, 'conda') && 'BASE_IMAGE=prefect-conda' ) || '' }}
            ${{ ( endsWith(matrix.flavor, 'kubernetes') && 'PREFECT_EXTRAS=[redis,kubernetes]' ) || '' }}
          load: true
          provenance: false
          project: v3l8p9flg1
